import Head from 'next/head'
import About from '../Components/About'
import Header from '../Components/Header'
import Nav from '../Components/Nav'
import Experience from '../Components/Experience'
import Portfolio from '../Components/Portfolio'
import Contact from '../Components/Contact'
import Footer from '../Components/Footer'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
      <Header />
      <About />
      <Experience />
      <Portfolio />
      <Contact />
      <Footer />
      <Nav />
    </div>
  )
}
